### ISSUE TITLE
cannot load such file -- bundler (LoadError)

### ISSUE THREAD

**Issue by znz** [k0kubun/benchmark_driver#10]
- Install ruby
- `gem install benchmark_driver`
- `ruby -e "require 'benchmark/driver'"` causes `cannot load such file -- bundler (LoadError)`

`benchmark_driver-0.8.2/lib/benchmark/runner/exec.rb` requires `bundler`, but `benchmark_driver` gem does not depend `bundler` gem.

**Comment by k0kubun** [comment]
resolved in https://github.com/k0kubun/benchmark_driver/commit/337b64bbba5106a3514beff5199c5ccb9f6d2b4d
